version: '3'
services:
  nginx:
    image: nginx
    volumes:
      - ./vhost.conf:/etc/nginx/conf.d/site.conf:Z
    ports:
      - "8700:8700"
  gunicorn:
    build:
      dockerfile: "Dockerfile-gunicorn"
      context: "."
    command: "gunicorn -w 4 -k sync --worker-connections=4 --access-logfile='-' --log-level=DEBUG --bind=0.0.0.0:8000 app:app"
    expose:
      - "8000"
